# Datei: .streamlit/secrets.toml

[mongodb]
# Hier den Schlüssel „uri“ verwenden und die ganze Verbindung in Anführungszeichen packen:
uri = "mongodb+srv://herterwaldemar:KZWFkubey2hIScdi@whcluster0.kxjuhm0.mongodb.net/weight_tracker?retryWrites=true&w=majority&appName=WeightTrackerApp"
 
